"""Phase 6c-2 naming layer. Re-exports mm_common.naming for desk packages.

Canonical module: ``mm_common.naming``. Config: ``config/desks/naming.yaml``.
Unknown slugs fail closed. Coord is not a publishing desk.
# Boundary comment: packages here must not import mm_execution (statement form is gated).
"""

from mm_common.naming import (
    ALERTS,
    ARTIFACT_TYPES,
    ASSEMBLE_CHANNEL,
    CHART_ARTIFACT,
    COORD,
    DAILY_BIAS,
    DQ_CHANNEL,
    EDGE_SCAN,
    GATES_IN_IC_RISK,
    IC_RISK,
    INTEL,
    INTEL_PACKET,
    MESH_DESKS,
    OFFICIAL_BRIEF,
    OPS,
    PIPELINE,
    PUBLISHING_DESKS,
    QUANT,
    RESEARCH,
    RETIRED_DESK_SLUGS,
    ROUTE_SLUGS,
    SLEEVE_MAP,
    STATE_CARD,
    LISTINGS,
    WATCHLIST,
    ArtifactName,
    NamedSlug,
    UnknownNameError,
    alerts_display,
    artifact_desk,
    artifact_display,
    as_config_dict,
    assert_config_matches,
    coord_display,
    desk_display,
    desk_short,
    desk_tier,
    publishing_slugs_help,
    require_artifact_type,
    require_named_slug,
    require_publishing_desk,
    require_route_slug,
    roster_lines,
    route_slugs_help,
    sleeve_display,
    sleeve_tier,
    telegram_header,
    with_telegram_header,
)

# Compatibility with Phase 6c-1 DESK_META: (display, tier) per publishing slug.
DESK_META: dict[str, tuple[str, str]] = {
    slug: (desk_display(slug), desk_tier(slug)) for slug in PUBLISHING_DESKS
}

__all__ = [
    "ALERTS",
    "ARTIFACT_TYPES",
    "ASSEMBLE_CHANNEL",
    "CHART_ARTIFACT",
    "COORD",
    "DAILY_BIAS",
    "DESK_META",
    "DQ_CHANNEL",
    "EDGE_SCAN",
    "GATES_IN_IC_RISK",
    "IC_RISK",
    "INTEL",
    "INTEL_PACKET",
    "MESH_DESKS",
    "OFFICIAL_BRIEF",
    "OPS",
    "PIPELINE",
    "PUBLISHING_DESKS",
    "QUANT",
    "RESEARCH",
    "RETIRED_DESK_SLUGS",
    "ROUTE_SLUGS",
    "SLEEVE_MAP",
    "STATE_CARD",
    "LISTINGS",
    "WATCHLIST",
    "ArtifactName",
    "NamedSlug",
    "UnknownNameError",
    "alerts_display",
    "artifact_desk",
    "artifact_display",
    "as_config_dict",
    "assert_config_matches",
    "coord_display",
    "desk_display",
    "desk_short",
    "desk_tier",
    "publishing_slugs_help",
    "require_artifact_type",
    "require_named_slug",
    "require_publishing_desk",
    "require_route_slug",
    "roster_lines",
    "route_slugs_help",
    "sleeve_display",
    "sleeve_tier",
    "telegram_header",
    "with_telegram_header",
]
